### ISSUE TITLE
Update 'setupRecyclerView' extension

### ISSUE THREAD

**Issue by dieter115** [appwise-labs/AndroidCore#18]
The extension function for the `setupRecyclerView` contains a parameter for a `DividerItemDecoration`.
To make it more abstract and more functional we should change this to accept a `RecyclerView.ItemDecoration` object.

**Comment by srijan960** [comment]
Hi I want to work on this issue and pretty new with android development can you help?

**Comment by ChristianoBolla-Appwise** [comment]
@srijan960 Hello, you are welcome to work on this issue. The idea is indeed to replace the parameter `DividerItemDecoration` with `RecyclerView.ItemDecoration`.

When you're done you may always create a PR so we can check it out and approve it if all is correct!
