### ISSUE TITLE
Room missing Gradle dependency for Room in README.md

### ISSUE THREAD

**Issue by RobbeJansensPXL** [appwise-labs/AndroidCore#213]
When ```kapt "androidx.room:room-compiler:2.4.2"``` is not added to the gradle file, the application shows ``Unexpected Error`` when trying to access the database. This dependency is not listed in the Readme.

**Comment by ChristianoBolla-Appwise** [comment]
Correct, I forgot to add it to the ReadMe. Nice catch!
