### ISSUE TITLE
Create a default QR code scanner

### ISSUE THREAD

**Issue by SibertSchurmans** [appwise-labs/AndroidCore#33]
My last projects ( and probably my next one too ) all worked with QR code scanners. There is an Appwise Barcode scanner file but it is a little bit outdated and Android now has its CameraX Jetpack library that can be used with this. 

I've already implemented a basic version but I can rewrite this for core if it's something you guys think we can use

**Comment by ChristianoBolla-Appwise** [comment]
I think this is a very good idea... maybe better to create a different library for that so we don't necessarily clutter Core with such functionalities, as I assume you'll have the need for some custom attributes, strings, colors,... (resources in general).

I noticed Jesse also made one in a project, maybe get together with him and see what can be done?

**Comment by ChristianoBolla-Appwise** [comment]
This has been picked up with the goals/rocks and also previously by Dieter and will be made into a standalone library named `ScanWise`
