### ISSUE TITLE
BaseDao should be an interface.

### ISSUE THREAD

**Issue by Jesse-Appwise** [appwise-labs/AndroidCore#34]
BaseDao should be an interface instead of an abstract class. Why? Using an abstract class, all queries in our Dao without body should be abstract functions. If you query entities with relations, these queries should be annotated as @Transaction. But if you do this, you het the error:` Method annotated with @Transaction must not be private, final, or abstract.`

With some @ChristianoBolla-Appwise magic, this is a possible solution.

![image (7)](https://user-images.githubusercontent.com/62235842/113401174-44505600-93a3-11eb-8364-b1501fe6eb18.png)
![image (6)](https://user-images.githubusercontent.com/62235842/113401177-44e8ec80-93a3-11eb-83e8-8bf00ccd15d6.png)
![image (5)](https://user-images.githubusercontent.com/62235842/113401179-45818300-93a3-11eb-8fab-e2dd135c0f43.png)

**Comment by Jesse-Appwise** [comment]
Edit: Apparently in some Room versions it

**Comment by ChristianoBolla-Appwise** [comment]
On second thought, I didn't test this, and if I'm not mistaken Room throws an error if you are using a tableName from a parameter or something like that... 🤔

**Comment by Jesse-Appwise** [comment]
It is possible when using RawQueries like @SibertSchurmans is already using. It is actually the same as he is using it now in his abstract class.

BUT 

The problem lies somewhere else. If you try to make a BaseDao as an interface, you come across this error: `DAO method can be annotated with only one of the following:Insert,Delete,Query,Update`. This makes these implementations of findAll or findAllById impossible to create. It is only possible if we restrict our query functions to Insert,Delete,(Base)Query or Update.

**Comment by Jesse-Appwise** [comment]
I still think this is something to consider. @ChristianoBolla-Appwise Remind me at the next meeting to bring this one up :)

**Comment by Jesse-Appwise** [comment]
EUREKA!

I found a way to fix the error: `Method annotated with @Transaction must not be private, final, or abstract.` for those abstract functions who aren't even defined as abstract in code! Just make them `open` 😅 . This makes this issue obsolete and thereby I will close this issue.
