### ISSUE TITLE
BaseEntity 'id' restricted to Int

### ISSUE THREAD

**Issue by Jesse-Appwise** [appwise-labs/AndroidCore#43]
If you want to use BaseEntity, your 'id' HAS to be an Int now. This should me more flexible with Any for instance.

**Comment by ChristianoBolla-Appwise** [comment]
@Jesse-Appwise Something simple like this can always be picked up by yourself as well. It's eventually coming in as a PR anyways so everyone is notified of the change ;)

**Comment by ChristianoBolla-Appwise** [comment]
Just as an FYI, I already created a PR for this change, so no need to worry about it now :D
